export default {
  "login": "madhuSudan27",
  "id": 122591446,
  "node_id": "U_kgDOB06Y1g",
  "avatar_url": "https://avatars.githubusercontent.com/u/122591446?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/madhuSudan27",
  "html_url": "https://github.com/madhuSudan27",
  "followers_url": "https://api.github.com/users/madhuSudan27/followers",
  "following_url": "https://api.github.com/users/madhuSudan27/following{/other_user}",
  "gists_url": "https://api.github.com/users/madhuSudan27/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/madhuSudan27/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/madhuSudan27/subscriptions",
  "organizations_url": "https://api.github.com/users/madhuSudan27/orgs",
  "repos_url": "https://api.github.com/users/madhuSudan27/repos",
  "events_url": "https://api.github.com/users/madhuSudan27/events{/privacy}",
  "received_events_url": "https://api.github.com/users/madhuSudan27/received_events",
  "type": "User",
  "site_admin": false,
  "name": "MadhuSudan Anand",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Algorithmic \r\nProblem Solver |Web Developer| DSA | VITian\r\n ",
  "twitter_username": null,
  "public_repos": 16,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2023-01-13T05:44:02Z",
  "updated_at": "2024-02-08T16:22:21Z"
};